// Next
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// React Hooks
import { useRef, useState } from "react";

// component
import Dropdown from "../components/Dropdown";
import Footer from "../components/footer";

// icons
import { AiFillCheckCircle } from "react-icons/ai";
import { IoLogoWhatsapp } from "react-icons/io";
import { FaEnvelope } from "react-icons/fa";
import { CgPhone } from "react-icons/cg";
import { CgFacebook } from "react-icons/cg";
import { AiOutlineTwitter } from "react-icons/ai";
import { AiFillInstagram } from "react-icons/ai";

// react scroll
import * as Scroll from "react-scroll";

export default function Home() {
  const about = useRef(null);
  const pricing = useRef(null);
  const contact = useRef(null);
  const scrollToElement = () => about.current.scrollIntoView();
  const scrollToElementPricing = () => pricing.current.scrollIntoView();
  const scrollToElementContact = () => contact.current.scrollIntoView();

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        {/* <div>
          <img src="blob2.svg" alt="" className="" />
        </div> */}
        {/* Header */}
        <div className="w-full">
          <div className="overflow-hidden w-[70vw] h-[70vw] absolute -left-[30vw] -top-[30vw]">
            <Image
              src="/blob.svg"
              layout="fill"
              objectFit="cover"
              alt=""
              className=""
            />
          </div>
          <div className="">
            <div className="hidden lg:flex gap-7 text-4xl justify-center ml-14 pt-8">
              <button
                type="button"
                onClick={scrollToElement}
                className="hover:cursor-pointer"
              >
                ABOUT
              </button>
              <button
                type="button"
                onClick={scrollToElementPricing}
                className="hover:cursor-pointer"
              >
                PRICING
              </button>
              <button
                type="button"
                onClick={scrollToElementContact}
                className="hover:cursor-pointer"
              >
                CONTACT
              </button>
            </div>
            <div className="hidden lg:flex absolute top-3 right-3">
              <Link href="/login">
                <button
                  type="button"
                  class="border border-indigo-500 bg-indigo-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-indigo-600 focus:outline-none focus:shadow-outline mx-auto"
                >
                  Login
                </button>
              </Link>
            </div>
            <div className="lg:hidden flex justify-end pt-3 pr-3">
              <Dropdown
                scrollToElement={scrollToElement}
                scrollToElementContact={scrollToElementContact}
                scrollToElementPricing={scrollToElementPricing}
              />
            </div>
            <p className="absolute lg:top-60 lg:right-60 hidden md:flex md:text-xl md:right-36 md:top-32 text-3xl w-[30vw]">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor,
              perferendis perspiciatis. Numquam architecto voluptatibus alias
            </p>
            <div className="text-3xl md:text-6xl  font-extrabold text-white ml-8 absolute">
              LOGO
            </div>
          </div>
          <div className="mt-[40vw] items-center md:mt-[30vw]">
            <p className="text-center font-semibold mx-3 md:hidden">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor,
              perferendis perspiciatis. Numquam architecto voluptatibus alias
            </p>
            <img
              src="undraw_innovative_re_rr5i.svg"
              alt=""
              className="w-2/3 mt-5 mx-auto md:ml-12 md:w-1/4 md:mt-0 lg:ml-24"
            />
            {/* <div className="overflow-hidden w-[70vw] h-[70vw] absolute -right-[30vw]">
              <Image
                src="/blob2.svg"
                layout="fill"
                objectFit="cover"
                alt=""
                className=""
              />
            </div> */}
          </div>
        </div>
        {/* about */}
        <div className="flex-row mt-[90vw] md:mt-[5vw]" ref={about}>
          <div className="text-center text-3xl font-semibold md:text-5xl">
            ABOUT US
          </div>
          <div className="md:flex md:mx-[10vw]">
            <div>
              <div className="mx-3 text-justify text-lg mt-10">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Repudiandae impedit reprehenderit error aspernatur dignissimos
                ut quam iusto unde fuga atque temporibus facilis dolorum culpa
                voluptatem ex, aliquid reiciendis debitis perferendis.
              </div>
              <div className="mx-3 text-justify text-lg mt-10">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia
                odit nemo officia pariatur nam itaque aliquam blanditiis
                eligendi, atque, optio velit ipsa sint placeat delectus magni,
                illo voluptates enim suscipit.
              </div>
            </div>
            <div className="mt-10">
              <img
                src="undraw_team_spirit_re_yl1v.svg"
                alt=""
                className="w-2/3 mt-5 mx-auto md:w-4/5"
              />
            </div>
          </div>
        </div>
        {/* Pricing */}
        <div className="flex-row mt-[30vw] md:mt-[10vw]">
          <div className="text-center text-3xl font-semibold " ref={pricing}>
            Pricing
          </div>
          <div className="mx-auto w-[70vw] md:w-[50vw] text-justify text-lg mt-10">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus
            rerum perferendis veniam iure nostrum saepe magnam voluptas earum
            aperiam!
          </div>
          {/* card */}
          <div className="flex-row md:flex md:gap-2 gap-6 w-full mt-4">
            <div className="w-[300px] h-fit md:h-[600px] rounded-lg shadow-xl mx-auto py-5">
              <div>
                <p className="font-bold text-center text-lg">Basic</p>
                <p className="text-sm">Sesuai untuk perusahaan rintisan</p>

                <div className="flex-col items-center">
                  <div className="flex text-center items-center gap-3 mt-5 font-semibold text-lg">
                    <AiFillCheckCircle className="text-green-600" />
                    <p>Mencatat barang masuk</p>
                  </div>
                  <div className="flex text-center items-center gap-3 mt-5 font-semibold text-lg">
                    <AiFillCheckCircle className="text-green-600" />
                    <p>Mencatat barang keluar</p>
                  </div>
                  <div className="flex text-center items-center gap-3 mt-5 font-semibold text-lg">
                    <AiFillCheckCircle className="text-green-600" />
                    <p>Mencatat hasil keuntungan</p>
                  </div>
                </div>
                <div className="flex mx-auto mt-6">
                  <button
                    type="button"
                    class="border border-indigo-500 bg-indigo-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-indigo-600 focus:outline-none focus:shadow-outline mx-auto"
                  >
                    Pilih Paket
                  </button>
                </div>
              </div>
            </div>
            <div className="w-[300px] h-fit md:h-[600px] md:justify-center rounded-lg shadow-xl mt-4 mx-auto">
              <div>
                <p className="font-bold text-center text-lg py-5">Bussiness</p>
                <p className="text-sm">Sesuai untuk perusahaan rintisan</p>
                <div className="">
                  <ul className="font-semibold text-lg">
                    <li className="flex gap-3 mt-5 items-center text-base">
                      <AiFillCheckCircle className="text-green-600" />
                      <p>Mencatat barang masuk dan keluar</p>
                    </li>
                    <li className="flex items-center">
                      <span className="flex gap-3 mt-5 items-center">
                        <AiFillCheckCircle className="text-green-600" />
                        <p>Mencatat keuangan</p>
                      </span>
                    </li>
                    <li className="flex items-center">
                      <span className="flex gap-3 mt-5 items-center">
                        <div>
                          <AiFillCheckCircle className="text-green-600" />
                        </div>
                        <p>Dapat menganalisa hasil penjualan dengan CHART</p>
                      </span>
                    </li>
                    <li className="flex gap-3 mt-5 items-center">
                      <AiFillCheckCircle className="text-green-600" />
                      <p>Support 24 X 7 Jam</p>
                    </li>
                  </ul>
                </div>
                <div className="flex mx-auto mt-6">
                  <button
                    type="button"
                    class="border border-indigo-500 bg-indigo-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-indigo-600 focus:outline-none focus:shadow-outline mx-auto"
                  >
                    Pilih Paket
                  </button>
                </div>
              </div>
            </div>
            <div className="w-[300px] h-fit md:h-[600px] rounded-lg shadow-xl mt-4 mx-auto">
              <div>
                <p className="font-bold text-center text-lg py-5">Bussiness</p>
                <p className="text-sm">Sesuai untuk perusahaan rintisan</p>
                <div className="">
                  <ul className="font-semibold text-lg">
                    <li className="flex items-center">
                      <span className="flex gap-3 mt-5 items-center">
                        <div>
                          <AiFillCheckCircle className="text-green-600" />
                        </div>
                        <p>Mencatat barang masuk dan keluar</p>
                      </span>
                    </li>
                    <li className="flex items-center">
                      <span className="flex gap-3 mt-5 items-center">
                        <div>
                          <AiFillCheckCircle className="text-green-600" />
                        </div>
                        <p>Mencatat keuntungan</p>
                      </span>
                    </li>
                    <li className="flex items-center">
                      <span className="flex gap-3 mt-5 items-center">
                        <div>
                          <AiFillCheckCircle className="text-green-600" />
                        </div>
                        <p>Dapat menganalisa hasil penjualan dengan chart</p>
                      </span>
                    </li>
                    <li className="flex items-center">
                      <span className="flex gap-3 mt-5 items-center">
                        <div>
                          <AiFillCheckCircle className="text-green-600" />
                        </div>
                        <p>Support 7 X 24 Jam</p>
                      </span>
                    </li>
                    <li className="flex items-center">
                      <span className="flex gap-3 mt-5 items-center">
                        <div>
                          <AiFillCheckCircle className="text-green-600" />
                        </div>
                        <p>Export data ke excel</p>
                      </span>
                    </li>
                    <li className="flex items-center">
                      <span className="flex gap-3 mt-5 items-center">
                        <div>
                          <AiFillCheckCircle className="text-green-600" />
                        </div>
                        <p>AI prediksi penghasilan</p>
                      </span>
                    </li>
                  </ul>
                </div>
                <div className="flex mx-auto mt-6">
                  <button
                    type="button"
                    class="border border-indigo-500 bg-indigo-500 text-white rounded-md px-4 py-2 m-2 transition duration-500 ease select-none hover:bg-indigo-600 focus:outline-none focus:shadow-outline mx-auto"
                  >
                    Pilih Paket
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* Contact */}
        <div className="" ref={contact}>
          <Footer />
          <div className="flex gap-10 w-full mx-auto mt-16 md:hidden">
            <img src="LogoHealthyMedBW.svg" alt="" />
            <div className="flex flex-col items-center gap-5 mt-7">
              <div className="text-5xl text-[#6B6B6B]">
                <IoLogoWhatsapp />
              </div>
              <div className="flex flex-col">
                <div className="text-[14px] font-bold">Chat Whatsapp</div>
                <div className="text-[16px]">+62 12345</div>
              </div>
            </div>
            <div className="flex flex-col items-center gap-5 mt-4">
              <div className="text-5xl text-[#6B6B6B]">
                <FaEnvelope />
              </div>
              <div className="flex flex-col">
                <div className="text-[14px] font-bold">Email</div>
                <div className="text-[16px]">contact@healthymed.com</div>
              </div>
            </div>
            <div className="flex flex-col items-center gap-5 mt-4">
              <div className="text-5xl text-[#6B6B6B]">
                <CgPhone />
              </div>
              <div className="flex flex-col">
                <div className="text-[14px] font-bold">Call Center</div>
                <div className="text-[16px]">+62 123451313</div>
              </div>
            </div>
          </div>
          <div className=""></div>
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
